id: I5509A428
ocr_import_info:
  timestamp: '2023-10-06T09:40:01.405771+00:00'
  batch_id: batch-b799
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharmakyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-10-06 14:06:51.309025+00:00
last_modified: 2023-10-06 14:06:51.309033+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W8464
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW8464
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རོང་སྟོན་ཤེས་བྱ་ཀུན་རིག་གི་རྒྱུད་བླ་མའི་འགྲེལ་པ།
  languages:
  - bo
  author: རོང་སྟོན་ཤེས་བྱ་ཀུན་རིག
statistics:
  ocr_word_mean_confidence_index: 0.9367735957640971
  ocr_word_median_confidence_index: 0.9850079700000001
bases:
  I1KG12615:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG12615
      total_pages: 202
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG12615.txt
    statistics:
      ocr_word_median_confidence_index: 0.9850079700000001
      ocr_word_mean_confidence_index: 0.9367735957640971
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
